global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'
          - 'blackbox-exporter:9115'

  - job_name: file_sd
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http  
    follow_redirects: true
    file_sd_configs:
      - files:
        - dynamic-config.yml
        refresh_interval: 5m

  - job_name: 'blackbox_efaktura2'
    metrics_path: /probe
    params:
      module: [efaktura2_mtls_post]  # The module name defined in the Blackbox Exporter config
    static_configs:
      - targets:
        #- efaktura2.no  # The endpoint you want to probe
        - google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115